//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystem.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReservationSystem.Utils.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den byl označen jako nehrající.
        /// </summary>
        internal static string CancellationOk {
            get {
                return ResourceManager.GetString("CancellationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše hromadná rezervace proběhal úsěšně..
        /// </summary>
        internal static string GroupReservationSuccessReason {
            get {
                return ResourceManager.GetString("GroupReservationSuccessReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ReloadOK {
            get {
                return ResourceManager.GetString("ReloadOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše rezervace byla úsěšně smazána..
        /// </summary>
        internal static string ReservationDeleteSucess {
            get {
                return ResourceManager.GetString("ReservationDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervováno!.
        /// </summary>
        internal static string ReservationSuccess {
            get {
                return ResourceManager.GetString("ReservationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše rezervace proběhal úsěšně..
        /// </summary>
        internal static string ReservationSuccessReason {
            get {
                return ResourceManager.GetString("ReservationSuccessReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraný stůl, je již bohužel rezervován..
        /// </summary>
        internal static string TableAlreadyPickedWarning {
            get {
                return ResourceManager.GetString("TableAlreadyPickedWarning", resourceCulture);
            }
        }
    }
}
