//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystem.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReservationSystem.Utils.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bohužel je již po skončení rezervací na tento den. V případě zájmu o rezervaci nám prosím zavolejte. Děkujeme.
        /// </summary>
        internal static string AfterDeadlineWarning {
            get {
                return ResourceManager.GetString("AfterDeadlineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den byl označen jako nehrající.
        /// </summary>
        internal static string CancellationOk {
            get {
                return ResourceManager.GetString("CancellationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše hromadná rezervace proběhal úsěšně..
        /// </summary>
        internal static string GroupReservationSuccessReason {
            get {
                return ResourceManager.GetString("GroupReservationSuccessReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozsahy dat se překrývají..
        /// </summary>
        internal static string RangesCollision {
            get {
                return ResourceManager.GetString("RangesCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím potvrďte vaši registraci kliknutím na tento &lt;a href={0}&gt;odkaz&lt;/a&gt;.
        /// </summary>
        internal static string RegistrationEmail {
            get {
                return ResourceManager.GetString("RegistrationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení vašeho účtu. AC SPARTA PRAHA - stolní tenis.
        /// </summary>
        internal static string RegistrationEmailSubject {
            get {
                return ResourceManager.GetString("RegistrationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ReloadOK {
            get {
                return ResourceManager.GetString("ReloadOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše rezervace byla úsěšně smazána..
        /// </summary>
        internal static string ReservationDeleteSucess {
            get {
                return ResourceManager.GetString("ReservationDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Potrvzujeme vaši rezervaci&lt;/h1&gt;&lt;table&gt;&lt;tr&gt;&lt;td&gt;DATUM&lt;/td&gt;&lt;td&gt;ČAS&lt;/td&gt;&lt;td&gt;STŮL&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;{0}&lt;/td&gt;&lt;td&gt;{1}&lt;/td&gt;&lt;td&gt;{2}&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;p&gt;Těšíme se na Vás v herně SPARTA PRAHA&lt;/p&gt;.
        /// </summary>
        internal static string ReservationEmailConfirmation {
            get {
                return ResourceManager.GetString("ReservationEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení rezervace SPARTA PRAHA STOLNÍ TENIS.
        /// </summary>
        internal static string ReservationEmailConfirmationSubject {
            get {
                return ResourceManager.GetString("ReservationEmailConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervováno!.
        /// </summary>
        internal static string ReservationSuccess {
            get {
                return ResourceManager.GetString("ReservationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše rezervace proběhal úsěšně. .
        /// </summary>
        internal static string ReservationSuccessReason {
            get {
                return ResourceManager.GetString("ReservationSuccessReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraný stůl, je již bohužel rezervován..
        /// </summary>
        internal static string TableAlreadyPickedWarning {
            get {
                return ResourceManager.GetString("TableAlreadyPickedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervujete si stoly 1-4. Nezapomeňte, že jde o stoly pro hráče AC Sparta a Vaše rezervace může být stornována. Více info. v Rezervačním řádu..
        /// </summary>
        internal static string TablesOneFour {
            get {
                return ResourceManager.GetString("TablesOneFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím napište administrátorovi chybu a popis toho co jste dělali. Děkuji.
        /// </summary>
        internal static string WriteAnAdministrator {
            get {
                return ResourceManager.GetString("WriteAnAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formát pro zadávání data je DD.MM (např. 01.05 nebo 18.11).
        /// </summary>
        internal static string WrongDateFormat {
            get {
                return ResourceManager.GetString("WrongDateFormat", resourceCulture);
            }
        }
    }
}
