// <auto-generated />
namespace ReservationSystem.MyMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddReservationName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReservationName));
        
        string IMigrationMetadata.Id
        {
            get { return "201712021654512_AddReservationName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
