// <auto-generated />
namespace ReservationSystem.MyMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DateRange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateRange));
        
        string IMigrationMetadata.Id
        {
            get { return "201808041338519_DateRange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
